"""Initial Schema

Revision ID: 17d6a60b305f
Revises: 
Create Date: 2025-12-13 21:33:47.610706

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.utils.settings import settings

# revision identifiers, used by Alembic.
revision: str = '17d6a60b305f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('repo_namespace', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.database_schema
    )
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_id'), 'agent_chat_sessions', ['id'], unique=False, schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_repo_namespace'), 'agent_chat_sessions', ['repo_namespace'], unique=False, schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_user_id'), 'agent_chat_sessions', ['user_id'], unique=False, schema=settings.database_schema)
    op.create_table('agent_chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], [f'{settings.database_schema}.agent_chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.database_schema
    )
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_chat_session_id'), 'agent_chat_messages', ['chat_session_id'], unique=False, schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_id'), 'agent_chat_messages', ['id'], unique=False, schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_message_order'), 'agent_chat_messages', ['message_order'], unique=False, schema=settings.database_schema)
    op.create_table('agent_chat_session_last_message_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('last_message_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], [f'{settings.database_schema}.agent_chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.database_schema
    )
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_session_last_message_order_chat_session_id'), 'agent_chat_session_last_message_order', ['chat_session_id'], unique=True, schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_session_last_message_order_id'), 'agent_chat_session_last_message_order', ['id'], unique=False, schema=settings.database_schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_session_last_message_order_id'), table_name='agent_chat_session_last_message_order', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_session_last_message_order_chat_session_id'), table_name='agent_chat_session_last_message_order', schema=settings.database_schema)
    op.drop_table('agent_chat_session_last_message_order', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_message_order'), table_name='agent_chat_messages', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_id'), table_name='agent_chat_messages', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_messages_chat_session_id'), table_name='agent_chat_messages', schema=settings.database_schema)
    op.drop_table('agent_chat_messages', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_user_id'), table_name='agent_chat_sessions', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_repo_namespace'), table_name='agent_chat_sessions', schema=settings.database_schema)
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_id'), table_name='agent_chat_sessions', schema=settings.database_schema)
    op.drop_table('agent_chat_sessions', schema=settings.database_schema)
    # ### end Alembic commands ###
