"""Data isolation schema change

Revision ID: ef043fbe1d9a
Revises: 17d6a60b305f
Create Date: 2026-01-07 15:45:10.813338

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from src.utils.settings import settings

# revision identifiers, used by Alembic.
revision: str = 'ef043fbe1d9a'
down_revision: Union[str, Sequence[str], None] = '17d6a60b305f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_chat_sessions', sa.Column('task_id', sa.Uuid(), nullable=False), schema=settings.database_schema)
    op.alter_column('agent_chat_sessions', 'repo_namespace',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               schema=settings.database_schema)
    op.create_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_task_id'), 'agent_chat_sessions', ['task_id'], unique=False, schema=settings.database_schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f'ix_{settings.database_schema}_agent_chat_sessions_task_id'), table_name='agent_chat_sessions', schema=settings.database_schema)
    op.alter_column('agent_chat_sessions', 'repo_namespace',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               schema=settings.database_schema)
    op.drop_column('agent_chat_sessions', 'task_id', schema=settings.database_schema)
    # ### end Alembic commands ###
